// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPayload is an autogenerated mock type for the IPayload type
type IPayload struct {
	mock.Mock
}

type IPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *IPayload) EXPECT() *IPayload_Expecter {
	return &IPayload_Expecter{mock: &_m.Mock}
}

// CustomValidatePayload provides a mock function with no fields
func (_m *IPayload) CustomValidatePayload() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CustomValidatePayload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IPayload_CustomValidatePayload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomValidatePayload'
type IPayload_CustomValidatePayload_Call struct {
	*mock.Call
}

// CustomValidatePayload is a helper method to define mock.On call
func (_e *IPayload_Expecter) CustomValidatePayload() *IPayload_CustomValidatePayload_Call {
	return &IPayload_CustomValidatePayload_Call{Call: _e.mock.On("CustomValidatePayload")}
}

func (_c *IPayload_CustomValidatePayload_Call) Run(run func()) *IPayload_CustomValidatePayload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IPayload_CustomValidatePayload_Call) Return(_a0 error) *IPayload_CustomValidatePayload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IPayload_CustomValidatePayload_Call) RunAndReturn(run func() error) *IPayload_CustomValidatePayload_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPayload creates a new instance of IPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPayload {
	mock := &IPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
