// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sql "github.com/rodericusifo/fiber-template/internal/app/model/database/sql"

	types "github.com/rodericusifo/fiber-template/pkg/types"
)

// IPermissionDatabaseSQLRepository is an autogenerated mock type for the IPermissionDatabaseSQLRepository type
type IPermissionDatabaseSQLRepository struct {
	mock.Mock
}

type IPermissionDatabaseSQLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IPermissionDatabaseSQLRepository) EXPECT() *IPermissionDatabaseSQLRepository_Expecter {
	return &IPermissionDatabaseSQLRepository_Expecter{mock: &_m.Mock}
}

// FirstPermission provides a mock function with given fields: query
func (_m *IPermissionDatabaseSQLRepository) FirstPermission(query *types.QuerySQL) (*sql.Permission, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FirstPermission")
	}

	var r0 *sql.Permission
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.QuerySQL) (*sql.Permission, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(*types.QuerySQL) *sql.Permission); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Permission)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.QuerySQL) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IPermissionDatabaseSQLRepository_FirstPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstPermission'
type IPermissionDatabaseSQLRepository_FirstPermission_Call struct {
	*mock.Call
}

// FirstPermission is a helper method to define mock.On call
//   - query *types.QuerySQL
func (_e *IPermissionDatabaseSQLRepository_Expecter) FirstPermission(query interface{}) *IPermissionDatabaseSQLRepository_FirstPermission_Call {
	return &IPermissionDatabaseSQLRepository_FirstPermission_Call{Call: _e.mock.On("FirstPermission", query)}
}

func (_c *IPermissionDatabaseSQLRepository_FirstPermission_Call) Run(run func(query *types.QuerySQL)) *IPermissionDatabaseSQLRepository_FirstPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.QuerySQL))
	})
	return _c
}

func (_c *IPermissionDatabaseSQLRepository_FirstPermission_Call) Return(_a0 *sql.Permission, _a1 error) *IPermissionDatabaseSQLRepository_FirstPermission_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IPermissionDatabaseSQLRepository_FirstPermission_Call) RunAndReturn(run func(*types.QuerySQL) (*sql.Permission, error)) *IPermissionDatabaseSQLRepository_FirstPermission_Call {
	_c.Call.Return(run)
	return _c
}

// NewIPermissionDatabaseSQLRepository creates a new instance of IPermissionDatabaseSQLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPermissionDatabaseSQLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPermissionDatabaseSQLRepository {
	mock := &IPermissionDatabaseSQLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
