// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRequestQuery is an autogenerated mock type for the IRequestQuery type
type IRequestQuery struct {
	mock.Mock
}

type IRequestQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *IRequestQuery) EXPECT() *IRequestQuery_Expecter {
	return &IRequestQuery_Expecter{mock: &_m.Mock}
}

// CustomValidateRequestQuery provides a mock function with no fields
func (_m *IRequestQuery) CustomValidateRequestQuery() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CustomValidateRequestQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRequestQuery_CustomValidateRequestQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CustomValidateRequestQuery'
type IRequestQuery_CustomValidateRequestQuery_Call struct {
	*mock.Call
}

// CustomValidateRequestQuery is a helper method to define mock.On call
func (_e *IRequestQuery_Expecter) CustomValidateRequestQuery() *IRequestQuery_CustomValidateRequestQuery_Call {
	return &IRequestQuery_CustomValidateRequestQuery_Call{Call: _e.mock.On("CustomValidateRequestQuery")}
}

func (_c *IRequestQuery_CustomValidateRequestQuery_Call) Run(run func()) *IRequestQuery_CustomValidateRequestQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IRequestQuery_CustomValidateRequestQuery_Call) Return(_a0 error) *IRequestQuery_CustomValidateRequestQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRequestQuery_CustomValidateRequestQuery_Call) RunAndReturn(run func() error) *IRequestQuery_CustomValidateRequestQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRequestQuery creates a new instance of IRequestQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRequestQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRequestQuery {
	mock := &IRequestQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
