// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sql "github.com/rodericusifo/fiber-template/internal/app/model/database/sql"

	types "github.com/rodericusifo/fiber-template/pkg/types"
)

// IUserResource is an autogenerated mock type for the IUserResource type
type IUserResource struct {
	mock.Mock
}

type IUserResource_Expecter struct {
	mock *mock.Mock
}

func (_m *IUserResource) EXPECT() *IUserResource_Expecter {
	return &IUserResource_Expecter{mock: &_m.Mock}
}

// FirstUser provides a mock function with given fields: query
func (_m *IUserResource) FirstUser(query *types.QuerySQL) (*sql.User, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FirstUser")
	}

	var r0 *sql.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.QuerySQL) (*sql.User, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(*types.QuerySQL) *sql.User); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.QuerySQL) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUserResource_FirstUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstUser'
type IUserResource_FirstUser_Call struct {
	*mock.Call
}

// FirstUser is a helper method to define mock.On call
//   - query *types.QuerySQL
func (_e *IUserResource_Expecter) FirstUser(query interface{}) *IUserResource_FirstUser_Call {
	return &IUserResource_FirstUser_Call{Call: _e.mock.On("FirstUser", query)}
}

func (_c *IUserResource_FirstUser_Call) Run(run func(query *types.QuerySQL)) *IUserResource_FirstUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.QuerySQL))
	})
	return _c
}

func (_c *IUserResource_FirstUser_Call) Return(_a0 *sql.User, _a1 error) *IUserResource_FirstUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUserResource_FirstUser_Call) RunAndReturn(run func(*types.QuerySQL) (*sql.User, error)) *IUserResource_FirstUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function with given fields: payload
func (_m *IUserResource) SaveUser(payload *sql.User) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sql.User) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUserResource_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type IUserResource_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - payload *sql.User
func (_e *IUserResource_Expecter) SaveUser(payload interface{}) *IUserResource_SaveUser_Call {
	return &IUserResource_SaveUser_Call{Call: _e.mock.On("SaveUser", payload)}
}

func (_c *IUserResource_SaveUser_Call) Run(run func(payload *sql.User)) *IUserResource_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sql.User))
	})
	return _c
}

func (_c *IUserResource_SaveUser_Call) Return(_a0 error) *IUserResource_SaveUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUserResource_SaveUser_Call) RunAndReturn(run func(*sql.User) error) *IUserResource_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewIUserResource creates a new instance of IUserResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserResource {
	mock := &IUserResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
