version: "3.9"
services:
  app:
    container_name: golang_fiber_container
    tty: true
    build:
      dockerfile: Dockerfile
      context: .
      target: build-release-stage
    ports:
      - 8081:${SERVER_PORT:-8080}
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - mysqldb
      - redisdb
    networks:
      - fiber_backend

  mysqldb:
    image: mysql:latest
    container_name: mysql_fiber_container
    environment:
      - MYSQL_DATABASE=${DATABASE_MYSQL_NAME}
      - MYSQL_USER=${DATABASE_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Jakarta
    ports:
      - 3307:3306
    volumes:
      - mysql_fiber_data:/var/lib/mysql
    networks:
      - fiber_backend

  # postgresdb:
  #   image: postgres:latest
  #   container_name: postgres_fiber_container
  #   environment:
  #     - POSTGRES_DB=${DATABASE_POSTGRES_NAME}
  #     - POSTGRES_USER=${DATABASE_POSTGRES_USERNAME}
  #     - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
  #   ports:
  #     - 5433:5432
  #   volumes:
  #     - postgres_fiber_data:/var/lib/postgresql/data
  #   networks:
  #     - fiber_backend

  redisdb:
    image: redis/redis-stack-server:latest
    container_name: redis_fiber_container
    environment:
      - REDIS_ARGS=--requirepass ${DATABASE_CACHE_REDIS_PASSWORD}
    ports:
      - 6380:6379
    volumes:
      - redis_fiber_data:/data
    networks:
      - fiber_backend

volumes:
  mysql_fiber_data:
  # postgres_fiber_data:
  redis_fiber_data:

# Networks to be created to facilitate communication between containers
networks:
  fiber_backend:
    driver: bridge
