// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package auth

import (
	"github.com/rodericusifo/fiber-template/internal/app/core/auth/service"
	resource2 "github.com/rodericusifo/fiber-template/internal/app/core/role/resource"
	"github.com/rodericusifo/fiber-template/internal/app/core/user/resource"
	"github.com/rodericusifo/fiber-template/internal/app/repository/database/sql/role"
	"github.com/rodericusifo/fiber-template/internal/app/repository/database/sql/user"
	"github.com/rodericusifo/fiber-template/internal/pkg/util/getter"
)

// Injectors from wire.go:

func AuthService() service.IAuthService {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iUserDatabaseSQLRepository := user.InitMysqlUserDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iUserResource := resource.InitUserResource(iUserDatabaseSQLRepository)
	iRoleDatabaseSQLRepository := role.InitMysqlRoleDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iRoleResource := resource2.InitRoleResource(iRoleDatabaseSQLRepository)
	iAuthService := service.InitAuthService(iUserResource, iRoleResource)
	return iAuthService
}
