// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/rodericusifo/fiber-template/internal/app/core/user/resource"
	"github.com/rodericusifo/fiber-template/internal/app/repository/database/sql/user"
	"github.com/rodericusifo/fiber-template/internal/pkg/util/getter"
)

// Injectors from wire.go:

func UserResource() resource.IUserResource {
	mysqlDatabaseSQLConnection := getter.GetMysqlDatabaseSQLConnection()
	iUserDatabaseSQLRepository := user.InitMysqlUserDatabaseSQLRepository(mysqlDatabaseSQLConnection)
	iUserResource := resource.InitUserResource(iUserDatabaseSQLRepository)
	return iUserResource
}
